### ISSUE TITLE
Timer's frame duration is scaled twice

### ISSUE THREAD

**Issue by barsoosayque** [mogemimi/pomdog#24]
In callback which is connected to *GameClock::OnTick*, *Timer* gets frame duration from the clock, scales it, scales it once more, and after that *Timer* updates total elapsed time with this value. This happens in [Timer.cpp#L21-L22](https://github.com/mogemimi/pomdog/blob/master/src/Application/Timer.cpp#L21-L22).

I think that initial frame duration should not be scaled, since it is available in `Timer::GetFrameDuration` method. Scaling should be performed when calculating elapsed time. In this solution, hovewer, `Timer::GetFrameDuration` just becomes a proxy-method for `GameClock::GetFrameDuration`, so I'm suggesting to remove it.

**Comment by mogemimi** [comment]
Hi, thank you for reporting the bug! Good catch! 🐛 👌 

Your idea sounds good. I will remove `Timer::GetFrameDuration()` function which causes confusing with scaling, in favour of using `GameClock::GetFrameDuration()` instead.
